POST http://localhost:8080/category HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "name": "Category 1",
    "description": "Category 1 description"
}

###

GET POST http://localhost:8080/category/{id} HTTP/1.1
Host: localhost:8080
Content-Type: application/json

###

GET POST http://localhost:8080/category HTTP/1.1
Host: localhost:8080
Content-Type: application/json

###

POST http://localhost:8080/product HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "name": "Product 1",
    "description": "Product 1 description",
    "price": 100,
    "image_url": "http://wwww.google.com",
    "category_id": {id}
}

###

GET http://localhost:8080/product HTTP/1.1
Host: localhost:8080
Content-Type: application/json

###

GET http://localhost:8080/product/{id} HTTP/1.1
Host: localhost:8080
Content-Type: application/json

###

GET http://localhost:8080/product/category/{id} HTTP/1.1
Host: localhost:8080
Content-Type: application/json
